#!/bin/sh

action=${1:-"default"}

if [ ! -e /var/service/pia ]; then
   echo "PIA service unavailable?"
   exit 1
fi

case $action in
    default)
        [ -e /usr/share/pia/selected.ovpn ] || ln -s /usr/share/pia/servers/'CA Toronto.ovpn' /usr/share/pia/selected.ovpn
        ;;
    off)
        sv down pia
        exit
        ;;
    *)
        if [ ! -e /usr/share/pia/servers/'$action'.ovpn ]; then
            echo "'$action' not found";
            exit 1
        fi
        ln -s /usr/share/pia/servers/'$action'.ovpn /usr/share/pia/selected.ovpn
        ;;
esac

sv down pia
sv up pia
