#!/bin/sh

action=${1:-"default"}

if [ ! -e /var/service/pia ]; then
   echo "PIA service unavailable?"
   exit 1
fi

case $action in
    auto)
        if [ -e /var/service/pia/down ]; then
            echo "Autostart PIA on boot."
            rm /var/service/pia/down
        else
            echo "Do not autostart PIA on boot."
            touch /var/service/pia/down
        fi
        ;;
    default)
        [ -e /usr/share/pia/selected.ovpn ] || ln -s "/usr/share/pia/servers/CA Toronto.ovpn" /usr/share/pia/selected.ovpn
        ;;
    off)
        sv down pia
        exit
        ;;
    *)
        if [ ! -e "/usr/share/pia/servers/$action.ovpn" ]; then
            echo "/usr/share/pia/servers/$action.ovpn not found";
            exit 1
        fi
        ln -sf "/usr/share/pia/servers/$action.ovpn" /usr/share/pia/selected.ovpn
        ;;
esac

sv down pia
sv up pia
